# -*- coding: utf-8 -*-
"""smartbin_droidcam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaz9-xgCylsVm6n9KmvKDsmU-12pk0BE
"""

# !unzip /content/dataset.v6i.yolov8.zip -d /content/data

# !pip install ultralytics==8.3.0

# !pip install ultralytics==8.3.0

# list all folders in current directory
# !ls -R | head -n 40

# !cat data/data.yaml

from ultralytics import YOLO

# load pretrained base model (nano for speed)
model = YOLO('yolov8n.pt')

# start training
results = model.train(
    data='/content/data/data.yaml',
    imgsz=640,
    epochs=40,
    batch=16,
    optimizer='AdamW',
    lr0=0.002,
    cos_lr=True,
    patience=15,
    project='smartbin_project',
    name='waste_v8_run'
)

from ultralytics import YOLO

model = YOLO('/content/smartbin_project/waste_v8_run/weights/best.pt')
metrics = model.val(data='/content/data/data.yaml', split='val')
print(metrics)

from google.colab import drive
drive.mount('/content/drive')

# !cp /content/smartbin_project/waste_v8_run/weights/best.pt /content/drive/MyDrive/
print("✅ best.pt saved to Google Drive!")

# ============================================================
# ✅ SmartBin Waste Detection – Precise Bounding Boxes
# ============================================================
from ultralytics import YOLO
import cv2
import random
import os
from IPython.display import Image, display

# --- 1️⃣ Load your best trained model ---
model = YOLO('/content/best.pt')

# --- 2️⃣ Assign distinct colors for each waste class ---
colors = {name: [random.randint(0, 255) for _ in range(3)]
          for name in model.names.values()}

# --- 3️⃣ Path to your test image folder ---
test_dir = '/content/data/test/images'  # <-- change if your test folder differs

# --- 4️⃣ Create folder for saving annotated images ---
os.makedirs('annotated_results', exist_ok=True)

# --- 5️⃣ Loop through test images for detection ---
for img_file in os.listdir(test_dir):
    img_path = os.path.join(test_dir, img_file)
    if not img_path.lower().endswith(('.jpg', '.png', '.jpeg')):
        continue

    # Run inference
    results = model(img_path, conf=0.5, iou=0.45, imgsz=640, verbose=False)

    # Get original image
    frame = results[0].orig_img.copy()

    # Draw refined bounding boxes manually
    for box in results[0].boxes:
        # Extract box coordinates, class, and confidence
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cls = int(box.cls[0])
        conf = float(box.conf[0])
        label = f"{model.names[cls]} {conf:.2f}"

        # Use a unique color for each class
        color = colors[model.names[cls]]

        # Draw precise rectangle with smooth corners
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 3)
        cv2.putText(frame, label, (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2, cv2.LINE_AA)

    # Save the annotated image
    save_path = f"annotated_results/{img_file}"
    cv2.imwrite(save_path, frame)

    # Display inside Colab (preview only first few)
    display(Image(filename=save_path))

# ==============================================================
# ♻️ SmartBin YOLOv8 — Precise Real-Time Detection (DroidCam Ready)
# ==============================================================

from ultralytics import YOLO
import cv2
import numpy as np
import random

# --- Load your best model ---
model = YOLO("/content/best.pt")  # <-- correct path

# --- 🔹 CHANGE THIS LINE for DROIDCAM feed ---
# Open DroidCam stream (make sure phone and PC are on same Wi-Fi)
# Example default port: 4747 (check DroidCam app for your IP)
SOURCE = "http://10.134.205.107:4747/video"  # Updated to provided IP

cap = cv2.VideoCapture(SOURCE)
if not cap.isOpened():
    raise SystemExit("❌ Could not connect to DroidCam. Check IP or app.")

print("✅ SmartBin YOLOv8 Real-Time Detection (DroidCam) Started")
print("Press 'Q' to quit.")

# --- Assign color per class for consistent visualization ---
colors = {name: [random.randint(0, 255) for _ in range(3)] for name in model.names.values()}

CONF_THRES = 0.55  # stricter = cleaner detections
IOU_THRES  = 0.4
IMGSZ = 640

while True:
    ret, frame = cap.read()
    if not ret:
        print("⚠️ Frame not received. Check DroidCam connection.")
        break

    # --------------- 🧠 ASPECT-RATIO PRESERVING PREPROCESSING ---------------
    h, w = frame.shape[:2]
    scale = IMGSZ / max(h, w)
    resized = cv2.resize(frame, (int(w * scale), int(h * scale)))
    top = (IMGSZ - resized.shape[0]) // 2
    bottom = IMGSZ - resized.shape[0] - top
    left = (IMGSZ - resized.shape[1]) // 2
    right = IMGSZ - resized.shape[1] - left
    padded = cv2.copyMakeBorder(resized, top, bottom, left, right, cv2.BORDER_CONSTANT, value=(114, 114, 114))
    # -----------------------------------------------------------------------

    # Run YOLOv8 inference
    results = model.predict(
        source=padded,
        conf=CONF_THRES,
        iou=IOU_THRES,
        imgsz=IMGSZ,
        verbose=False
    )

    # Draw precise bounding boxes
    for box in results[0].boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cls = int(box.cls[0])
        conf = float(box.conf[0])
        label = f"{model.names[cls]} {conf:.2f}"
        color = colors[model.names[cls]]

        cv2.rectangle(padded, (x1, y1), (x2, y2), color, 2)
        cv2.putText(padded, label, (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2, cv2.LINE_AA)

    cv2.imshow("♻️ SmartBin YOLOv8 – Precise Detection (DroidCam)", padded)

    # Quit on 'Q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
print("👋 Stream closed.")

